# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rpineda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: image-resizer
# "service" is the name of this project. This will also be added to your AWS resource names.
service: image-resizer

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

package:
  exclude:
    - package-log.json

functions:
  imageResizerNode:
    handler: nodeHandler.imageResizer
    timeout: 900
    events:
      - httpApi:
          path: /
          method: post
    environment:
      S3_BUCKET_NAME: ${env.S3_BUCKET_NAME}
      ACCESS_KEY_ID: ${env.ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env.SECRET_ACCESS_KEY}
  imageResizerBun:
    handler: bunHandler.imageResizer
    runtime: provided.al2
    timeout: 900
    architecture: arm64
    layers:
      - arn:aws:lambda:us-east-2:256727551815:layer:bun:1
    events:
      - httpApi:
          path: /bun
          method: post
    environment:
      S3_BUCKET_NAME: ${env.S3_BUCKET_NAME}
      ACCESS_KEY_ID: ${env.ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env.SECRET_ACCESS_KEY}