# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rpineda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: xml-parser
# "service" is the name of this project. This will also be added to your AWS resource names.
service: xml-parser

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  xmlParserNode:
    handler: nodeHandler.xmlParser
    events:
      - httpApi:
          path: /
          method: post
  xmlParserBun:
    handler: bunHandler.xmlParser
    runtime: provided.al2
    architecture: arm64
    layers:
      - arn:aws:lambda:us-east-2:256727551815:layer:bun:1
    events:
      - httpApi:
          path: /bun
          method: post
