# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rpineda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dijsktra-solver
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dijsktra-solver

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  dijkstraSolverNode:
    handler: nodeHandler.dijkstraSolver
    events:
      - httpApi:
          path: /
          method: get
  dijkstraSolverBun:
    handler: bunHandler.dijkstraSolver
    runtime: provided.al2
    architecture: arm64
    layers:
      - arn:aws:lambda:us-east-2:256727551815:layer:bun:1
    events:
      - httpApi:
          path: /bun
          method: get
